language: java
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
    mvn clean deploy --settings target/travis/settings.xml;
else
    mvn clean verify --settings target/travis/settings.xml;
fi"

jdk:
  - openjdk7

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "G7lqKoWyQNM404n6cfSG2ByJcbxfa6F/5pYfMjtKT30a8Mvcz3zl8e5Cqnb1Gta5JJotjUBrxZxWIGH80aK8qys5b9TUpzqsPyR/JZDGfET/+zsLzoMHJsC7b/L2eGGFPgueQ9HHUt6/Z+UwXJZcmyahrJKykhylA+UYyoCE9YU="
    - secure: "Hb7u2kgN01HHS21sDozf7trqIABQA+CV7xwJbdW9+KJg9L4AuVyd3Lq4qSASsmKIKT41vutGTwjY6O/Z9bR2JvG+RuJ+WyRmw9HVTnE7d8/anpGTnJb6Sq6mgAjtvfar/Soxr8yg/nFOJZDG8JN8HKQF+M2DBRv/Cq1O6wOyrU8="
