language: java
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: ' if [ ${TRAVIS_PULL_REQUEST} = ''false'' ]; then mvn clean deploy --settings
  target/travis/settings.xml; else mvn clean verify --settings target/travis/settings.xml;
  fi'
jdk:
- openjdk7
branches:
  only:
  - master
env:
  global:
  - secure: ZQU2OkS8DpYwBll52KdqDBdbF7RCpFYV+Nj3JqwAx3KFoYT7c42fjgyNKXWsttJOtc+vJL/i2zwn0GRmLAPSWKR2LMiYTH4i6mQwKb244ktydTFSoFQe1N3UVflmjqTn3Eq5D4mFiY0MO+PNjNXbejl2WA6aWopa8ANXbqJHFYk=
  - secure: hGI6ryjh8QxxxZRY6Kvaao7hzJiTEBhLgAT3xZBV5tgD0SodwerPgprYjwJnKbdGyE55qtjzL1/MoN7OHHubJQ09NjqDtmlKDTO8E4nNR2An0REf/+Cg2bGpbucxV4bII9oY+hrmguNFmw8jaJ3rfamnnuPVrSgTyGLW4YuhFKc=
