language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean deploy --settings target/travis/settings.xml; 
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "d3IGzpongXsYshHQi4C0g+O7LpAeZBSxZtcINPRJLqcpj7Xeu0qE0jiFLWQUD7B/qyHHUMnEsX3cWMNPRJM6AQb7V00TdIADsp34wI79klmeTYo0giK8B516+d+02VT6F0m0Lz2/yhs6BsrG6yle2+oFk7rvEYp/6gP+gQP6/+Q="
    - secure: "XLpMDm1OmJVfmMFdua1mprIu1/ddeIFcGlOsGgrZ/cducGmLueeB+fODLlc8VKFUkmm1kpC9ugkNQgazaPeWvys+R7pqIAv8cWp8jfKPKAsPeUmnA1Y3zAqnYKmL7qdjVNMb08ikpW/MwqxX8t+GdPpZg+MKomvD3kHRdTF0VWA="
